### ISSUE TITLE
Documentation issue: Please could you provide some documentation on how to use ContainerPatch.

### ISSUE THREAD

**Issue by rkazak** [kumahq/kuma-website#1010]

**Comment by jakubdyszkiewicz** [comment]
> Triage: provide more examples with complex objects

Example
```
apiVersion: kuma.io/v1alpha1
kind: ContainerPatch
metadata:
  name: container-patch-tmpfs
  namespace: kong-mesh-system
spec:
  sidecarPatch:
    - op: add
      path: /volumeMounts/-
      value: '{ "mountPath": "/tmp", "name":"tmpfs" }'
```
