### ISSUE TITLE
document that on universal you can't do outbound with tags

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-website#1310]
### Description

as shown with github.com/kumahq/kuma/issues/6546

**Comment by lahabana** [comment]
Apparently we can. Let's double check and discuss...

**Comment by jakubdyszkiewicz** [comment]
I double checked. It works.

I spinned up this
```
type: Dataplane
mesh: default
name: web-01
networking:
  address: 192.168.1.35
  gateway:
    tags:
      kuma.io/service: web
      version: v1
  outbound:
  - port: 33033
    tags:
      kuma.io/service: backend
  - port: 33034
    tags:
      kuma.io/service: backend
      version: "2.0"
  admin:
    port: 9902
metrics:
  type: prometheus
  conf:
    skipMTLS: true
    port: 5670
    path: /metrics
```

and

```
type: Dataplane
mesh: default
name: backend-01
networking:
  admin:
    port: 9901
  #address: 192.168.1.35
  address: 127.0.0.1
  inbound:
  - port: 21011
    servicePort: 21012
    serviceAddress: 127.0.0.1
    tags:
      kuma.io/service: backend
      version: "2.0"
      kuma.io/protocol: http
```
I was able to use both outbounds.
