### ISSUE TITLE
Improve OTEL docs on body format

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma-website#1538]
### Description

Context https://github.com/kumahq/kuma/issues/8348

A user as well as me got confused how to use `body` field. We need examples like this
```
apiVersion: kuma.io/v1alpha1
kind: MeshAccessLog
metadata:
  name: default
  namespace: kuma-system
spec:
  targetRef:
    kind: Mesh
  from:
    - targetRef:
        kind: Mesh
      default:
        backends:
          - type: OpenTelemetry
            openTelemetry:
              endpoint: otel-collector.observability.svc:4317
              body:
                kvlistValue:
                  values:
                  - key: "mesh"
                    value:
                      stringValue: "%KUMA_MESH%"
```
