### ISSUE TITLE
Expand installer test matrix

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-website#1647]
### Description

We could have even bigger matrix, like this one:

```
        arch:
          - amd64
          - aarch64 # arm64
        os:
          - amazonlinux:2022
          - archlinux:latest
          - debian:bookworm
          - fedora:latest
          - redhat/ubi8:8.6
          - ubuntu:22.04
        version:
          - preview
          - 2.2.0
          - 0.0.0-preview.v76e03eb68
        productVersion:
          - kuma
          - km
```

to cover more cases. We would have to generalise `installer-sh-arm64` job to accomodate for all arch/os/version/products
