### ISSUE TITLE
MeshService toggle in policy_yaml

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-website#1919]
### Description

On the last meeting with @lahabana we discussed changes to docs with relation to the changes to `MeshService`.

We would like to introduce a checkbox that would convert from "old style" MeshServcie:

```
  targetRef:
    kind: MeshService
    name: web_kuma-demo_svc_8080
```

To new style:

```
  targetRef:
    kind: MeshService
    namespace: kuma-demo
    name: web
    sectionName: http
```

It could look something like this:

![image](https://github.com/user-attachments/assets/16a59e8a-47bb-4a95-875a-eaaa802bd978)

**We'd like the checkbox value to be persisted for each session.**

We can supply the code to convert between the two. One thing that would be problematic is `sectionName` right?

This idea came from trying to figure out this issue: https://github.com/kumahq/kuma-website/issues/1892.
