### ISSUE TITLE
Document flagger with GatewayAPI 

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-website#1946]
[Look here for explanation](https://github.com/kumahq/kuma-website/issues/1946)

### What happened?

I think there are three problems with it:
1. This does not work https://github.com/fluxcd/flagger/blob/133fdecf56b2983f69cf06cbdeb372f988d89343/docs/gitbook/tutorials/kuma-progressive-delivery.md?plain=1#L34 it should be `kubectl label namespace test kuma.io/sidecar-injection=enabled` otherwise pods to not have sidecars
2. Default traffic permission is missing

```
apiVersion: kuma.io/v1alpha1
kind: TrafficPermission
mesh: default
metadata:
  name: allow-all-traffic
spec:
  sources:
    - match:
        kuma.io/service: '*'
  destinations:
    - match:
        kuma.io/service: '*'
```

thats why load tester can't access the podinfo service

3. Flagger integration should be using `MeshHTTPRoute`

FYI @aryan9600
