### ISSUE TITLE
Improve `MeshRetry` docs and add missing `MeshHTTPRoute` targetRef

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma-website#2110]
### Description

The `retryOn` section in the `MeshRetry` docs is hard to understand. It’s not clear what each option means or how they work together. For example, when I tried to check if `503` responses were covered, I had to look at the Envoy docs because our docs didn’t help. The explanation about combining status codes (`5xx`, `429`) and methods (`HttpMethodGet`) was confusing and made it seem like they couldn’t be used together.

Also, add `MeshHTTPRoute` should be added to the supported top level `targetRef`s

### Suggested Fix

Update the [`retryOn` section in the `MeshRetry` docs](https://kuma.io/docs/2.9.x/policies/meshretry/#retry-on) to clearly explain what each option does and how they can be combined.

### Example Policy

```yaml
type: MeshRetry
mesh: default
name: retry-policy
spec:
  targetRef:
    kind: Mesh
  to:
  - targetRef:
      kind: MeshService
      name: service-name
    default:
      http:
        retryOn:
        - Reset
        - ConnectFailure
        - HttpMethodGet
```
