### ISSUE TITLE
Document how `to[].targetRef.sectionName` is resolved to real resources

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-website#2163]
### Description

In outbound policies, we can use `sectionName`:

```yaml
to:
  - targetRef:
      kind: MeshService
      name: backend
      sectionName: port-name # or stringify port's value like "8080"
```

we need to document how Kuma maps `sectionName` to real MeshService (or MeshMultiZoneService) ports
