### ISSUE TITLE
Improve MeshTrace docs

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma-website#2183]
### Description

When configuring a delegated gateway with MeshTrace, a user noticed that they had to add tags to the policy to properly aggregate traces. We should document that these tags are required.

```yaml
type: MeshTrace
mesh: default
name: default
labels:
  kuma.io/mesh: default
spec:
  default:
    backends:
      - type: OpenTelemetry
        openTelemetry:
          endpoint: 10.36.147.152:4317
    tags:
      - name: version
        header:
          name: x-version
      - name: b3-traceid
        header:
          name: x-b3-traceid
      - name: b3-parent-span-id
        header:
          name: x-b3-parent-span-id
```
