### ISSUE TITLE
MLBS shows `_port` in the output

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma-website#2317]
### Kuma Version

latest

### Describe the bug

This example: https://kuma.io/docs/2.10.x/policies/meshloadbalancingstrategy/#route-within-the-local-zone-equally-but-specify-cross-zone-order

Shows `_port`, which I don't think it should. Should we even be using `policy_yaml` / `use_meshservice=true` for this one?

```yaml
apiVersion: kuma.io/v1alpha1
kind: MeshLoadBalancingStrategy
metadata:
  name: cross-zone-backend
  namespace: kuma-demo
  labels:
    kuma.io/mesh: default
spec:
  to:
  - targetRef:
      kind: MeshMultiZoneService
      name: backend
      namespace: kuma-demo
      sectionName: http
      _port: 8080
    default:
      localityAwareness:
        crossZone:
          failover:
          - to:
              type: Only
              zones:
              - us-1
          - to:
              type: AnyExcept
              zones:
              - us-2
              - us-3
          - to:
              type: Any
          failoverThreshold:
            percentage: 25
```
