### ISSUE TITLE
Document variables in kumactl apply -f

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma-website#269]
You can parametrize resource for kumactl like this:
```
mtls:
  backends:
  - name: vault-1
    type: {{ caType }}
    dpCert:
      rotation:
        expiration: 10h
name: default
type: Mesh
```
`kumactl apply -f ~/res/mesh.yaml -v caType=builtin`

I see no doc for this feature
