### ISSUE TITLE
Improve documentation: Traffic Metrics Page (kuma_sd_config)

### ISSUE THREAD

**Issue by Dh0ren** [kumahq/kuma-website#602]
### Description

Hello after using the Kuma documentation, I would like to give you my feedback on the part that was the most confusing for me, the kuma-sd config part of the Traffic Metrics page

- In order to avoid any confusion, I think it would be interesting to add a new part / section which specifies that to scrape the metrics from the control-plane, it is necessary to add a new job to the YML of our hosted prometheus

- I also think it could be interesting to separate more explicitly the kuma_sd_config / Create part a "Use hosted Prometheus" section to improve the readability, where it is specified that it allows to not to add a Prom instance that would run alongside each k8s cluster for example .

- I saw that the proposal "_feat(kuma-prometheus-sd) add deprecation notice #2994_" has been merged, adding the test documentation would be great!

https://github.com//kumahq/kuma/pull/2994

- Also, I think it might be useful to give the github link of the example made by Austince to use Kuma SD, "_kuma-sd playground_": https://github.com/austince/kuma-sd-playground. (Adding a new job in  _prometheus > config.yaml_ to scrape CP will be great)

Personally as a beginner it helped me to understand better and allowed me to advance in my deployment.

For information, in order to get the metrics, I personally used this job:
```
- job_name: kubernetes-service-endpoints
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - devoteam
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scrape
      - action: replace
        regex: (https?)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_scheme
        target_label: __scheme__
      - action: replace
        regex: (.+)
        source_labels:
        - __meta_kubernetes_service_annotation_prometheus_io_path
        target_label: __metrics_path__
      - action: replace
        regex: ([^:]+)(?::\d+)?;(\d+)
        replacement: $1:$2
        source_labels:
        - __address__
        - __meta_kubernetes_service_annotation_prometheus_io_port
        target_label: __address__
      - action: labelmap
        regex: __meta_kubernetes_service_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: kubernetes_namespace
      - action: replace
        source_labels:
         - __meta_kubernetes_service_name
         target_label: kubernetes_name
       - action: replace
         source_labels:
         - __meta_kubernetes_pod_node_name
         target_label: kubernetes_node
```
However, I think most of my confusion stems from my lack of experience in the field. Thanks
