### ISSUE TITLE
Explain the need for a NetworkPolicy on k8s

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-website#703]
### Description

Sometimes users need a NetworkPolicy when using flannel etc for the webhook.

Might be worth explaining this in the docs.
Does it fit in a k8s troubleshooting section? Somewhere else?
```
apiVersion: http://networking.k8s.io/v1
metadata:
  name: allow-same-svc-call
  namespace: abcd-poc
spec:
  podSelector:
    matchLabels:
      http://app.kubernetes.io/name: "kong-mesh"
  ingress:
  - from:
    - ipBlock:
        cidr: x.x.x.x/28
    ports:
    - port: 5443
```
