### ISSUE TITLE
Limitation when apply TrafficPermission, FaultInjection and RateLimit on ZoneEgress

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma-website#727]
### What happened?

Policies such as Fault Injections, Rate Limit, and Traffic Permissions support arbitrary tags in Destination, but we lose this
information if placing policies in the map just by Service's name. Example:
```
type: ExternalService
mesh: default
name: es-v1
tags:
  kuma.io/service: my-external-service
  version: v1

type: ExternalService
mesh: default
name: es-v2
tags:
  kuma.io/service: my-external-service
  version: v2

type: FaultInjection
mesh: default
name: fi1
destinations:
- match:
   kuma.io/service: my-external-service
   version: v1
...

type: FaultInjection
mesh: default
name: fi2
destinations:
- match:
   kuma.io/service: my-external-service
   version: v2
...
```

Then we'll build a map: `"my-external-service" -> ["fi1", "fi2"]`
And lately, we'll place fi1 and fi2 on all fault injections filter chains for `my-external-service` (in `external_services_generator.go`)
