### ISSUE TITLE
document mesh gateway instance service annotation

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma-website#892]
### Description

Feature is in but not documented!

```
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: foo-gateway
  namespace: default
spec:
  replicas: 1
  serviceType: LoadBalancer
  tags:
    kuma.io/service: foo-gateway
  serviceTemplate:
    metadata:
      annotations:
        service.beta.kubernetes.io/aws-load-balancer-internal: "true"
```
